# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/ldis_task1_bd/ldis_task1_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ldis_task1_bd || ORIG_REF_NAME==ldis_task1_bd} -quiet] -quiet

# IP: bd/ldis_task1_bd/ip/ldis_task1_bd_clk_wiz_0_0/ldis_task1_bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ldis_task1_bd_clk_wiz_0_0 || ORIG_REF_NAME==ldis_task1_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ldis_task1_bd/ip/ldis_task1_bd_SamplingWrapper_0_0/ldis_task1_bd_SamplingWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ldis_task1_bd_SamplingWrapper_0_0 || ORIG_REF_NAME==ldis_task1_bd_SamplingWrapper_0_0} -quiet] -quiet

# IP: bd/ldis_task1_bd/ip/ldis_task1_bd_CTRLWrapper_0_0/ldis_task1_bd_CTRLWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ldis_task1_bd_CTRLWrapper_0_0 || ORIG_REF_NAME==ldis_task1_bd_CTRLWrapper_0_0} -quiet] -quiet

# IP: bd/ldis_task1_bd/ip/ldis_task1_bd_ila_0_0/ldis_task1_bd_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ldis_task1_bd_ila_0_0 || ORIG_REF_NAME==ldis_task1_bd_ila_0_0} -quiet] -quiet

# IP: bd/ldis_task1_bd/ip/ldis_task1_bd_DspWrapper_0_0/ldis_task1_bd_DspWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ldis_task1_bd_DspWrapper_0_0 || ORIG_REF_NAME==ldis_task1_bd_DspWrapper_0_0} -quiet] -quiet

# IP: bd/ldis_task1_bd/ip/ldis_task1_bd_OutputWrapper_0_0/ldis_task1_bd_OutputWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ldis_task1_bd_OutputWrapper_0_0 || ORIG_REF_NAME==ldis_task1_bd_OutputWrapper_0_0} -quiet] -quiet

# XDC: bd/ldis_task1_bd/ldis_task1_bd_ooc.xdc
