@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Apr 09 00:29:59 +0200 2019
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim Sampling_Interface_TB_behav -key {Behavioral:SPI_SIM:Functional:Sampling_Interface_TB} -tclbatch Sampling_Interface_TB.tcl -protoinst "protoinst_files/ldis_task1_bd.protoinst" -view D:/DEV/ldis_task1/_DAFR_/vivado/Sampling_Interface_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
